name: elephant

channels:
  - conda-forge  # required for MPI

dependencies:
  - python>=3.8

  - mpi4py
  - numpy>=1.19.5
  - scipy
  - tqdm
  - scikit-learn
  - statsmodels
  - jinja2
  - pip:
    - neo>=0.10.0
    - nixio>=1.5.0
    # - viziphant
    # neo, viziphant can be removed once it is integrated into requirements-tutorials.txt
